# Automatically generated by Pynguin.
import pytest
from todoist_cli import new_task


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"f\x1e]\xda)\x87Z\xe7\x10"
    new_task.find_label_ids(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    tuple_0 = ()
    new_task.preprocess_task_metadata(tuple_0, tuple_0, tuple_0, tuple_0, tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b""
    tuple_0 = new_task.preprocess_task_metadata(
        bytes_0, bytes_0, bytes_0, bytes_0, bytes_0
    )
    assert new_task.priority_to_num == {"P1": 4, "P2": 3, "P3": 2, "P4": 1}
    new_task.find_project_id(tuple_0, tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "$N7<"
    new_task.preprocess_task_metadata(str_0, str_0, str_0, str_0, str_0)
